<header>
        <div class="nav-logo">
            <img src="../images/UrbanPulseDynamicslogo.png" alt="UrbanPulse Dynamics Logo" style="margin-right: 10px;">
            <div>
                <span id = "glow" class="logo-main">UrbanPulse</span>
                <span class="logo-sub">Dynamics</span>
            </div>
        </div>

        <div class="search-bar"> <!-- search bar -->
            <label for="search" class="sr-only">Search</label>
            <input type="text" id="search" placeholder="Search...">
            <button aria-label="Search"><i class='bx bx-search'></i></button>
        </div>

        <nav>
            <a href="../Index/index.php" class="nav-link active">HOME</a>
            <a href="../Jobs/jobs.php" class="nav-link">JOBS</a>
            <a href="../Apply/Apply.php" class="nav-link">APPLY</a>
            <a href="../About/about.php" class="nav-link">ABOUT</a>
            <a href="../manage.php">MANAGE</a>
        </nav>
</header>