<header>
    <div class="nav-logo">
            <img src="../images/UrbanPulseDynamicslogo.png" alt="UrbanPulse Dynamics Logo" style="margin-right: 10px;">
                <div>
                    <span id = "glow" class="logo-main">UrbanPulse</span>
                    <span class="logo-sub">Dynamics</span>
                </div>
        </div>
        <nav>
            <a href="../Index/index.php">HOME</a>
            <a href="../Jobs/jobs.php">JOBS</a>
            <a href="../Apply/Apply.php">APPLY</a>
            <a href="../About/about.php">ABOUT</a>
        </nav>
</header>