<header>
    <div class="nav-logo">
        <img src="/WebCraftersProject2/images/UrbanPulseDynamicslogo.png" alt="UrbanPulse Dynamics logo">
        <div>
            <span id="glow" class="logo-main">UrbanPulse</span>
            <span class="logo-sub">Dynamics</span>
        </div>
    </div>
    <nav>
        <a href="../index.php">HOME</a>
        <a href="../jobs.php">JOBS</a>
        <a href="../Apply.php">APPLY</a>
        <a href="../about.php">ABOUT</a>
        <a href="../manage.php">MANAGE</a>
    </nav>
</header>