<nav class="navbar"> <!-- navigation bar -->
        <div style="display: flex;  flex-direction: column; gap: 8px; align-items: flex-start;"> <!-- logo and search container -->
            <div class="nav-logo"> <!-- logo section -->
            <img src="../images/UrbanPulseDynamicslogo.png" alt="UrbanPulse Dynamics Logo" style="margin-right: 10px;">
                <div> 
                    <span class="logo-main">UrbanPulse</span>
                    <span class="logo-sub">Dynamics</span>
                </div>
            </div>

            <div class="search-bar"> <!-- search bar -->
                <label for="search" class="sr-only">Search</label>
                <input type="text" id="search" placeholder="Search...">
                <button aria-label="Search"><i class='bx bx-search'></i></button>
            </div>
        </div>

        <nav>
            <a href="../Index/index.php" class="nav-link active">HOME</a>
            <a href="../Jobs/jobs.php" class="nav-link">JOBS</a>
            <a href="../Apply/Apply.php" class="nav-link">APPLY</a>
            <a href="../About/about.php" class="nav-link">ABOUT</a>
        </nav>
    </nav>